name: Stage Deployment

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Deploying to Stage'
        # required: true
        type: string
        default: 'Stage'

  # workflow_dispatch:
  #   inputs:
  #     Environment:
  #       description: 'Select environment to deploy'
  #       required: true
  #       type: choice
  #       options:
  #         - Stage
  push:
    branches:
      - stage
    paths-ignore:
      - '*.md'
